### ISSUE TITLE
Error: lexical error: (?)

### ISSUE THREAD

**Issue by cpwebster** [dickoa/rgeoboundaries#20]
Hello!

I've been using rgeoboundaries to generate maps over the past year and have loved this package! However, yesterday I came across this error:

```
> colombia_bound <- rgeoboundaries::geoboundaries("Colombia")
Error: lexical error: invalid char in json text.
                                                  <!DOCTYPE HTML PUBLIC "-//IETF/
                                   (right here) ------^
```

I've never run into this issue until recently, and I've used this same line of code many times before. I'm using R version 4.2.2, any ideas to what could be causing this error? Thank you for your help!

**Comment by DanRunfola** [comment]
Hi @cpwebster - try reinstalling the package from this repository (make sure you detach it / unload it first):
remotes::install_github("wmgeolab/rgeoboundaries")

After two years of extensions we deprecated our old/original geoBoundaries API, which the original rgeoboundaries package relied on.  However, we also updated the package to use our "new" API (nearly 5 years old now itself!), so updating should fix it for you.  As an added bonus, you'll get data that's been updated in the last ~4 years or so (the old API was frozen to gB 3.0 - we're at 6.0 now!). 

Note that we aren't R folk over here (we're mostly a python shop), so if you run into issues please don't hesitate to ping back here.  We've done some testing, and a few other users have reported issues we've fixed, so hopefully everything will go just fine.

Best,
Dan

**Comment by cpwebster** [comment]
Hi @DanRunfola ,

Thanks so much for your response! I tried what you suggested, the uninstall, reinstall, and loading the package again, but unfortunately, I'm still getting the same issue..... here is my workflow:

```
> remove.packages("rgeoboundaries", lib="~/R/x86_64-pc-linux-gnu-library/4.2")
> remotes::install_github("wmgeolab/rgeoboundaries")
> library(rgeoboundaries)
> #fetch Colombia boundary and read in elevation data
> colombia_bound <- rgeoboundaries::geoboundaries("Colombia")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
```

I am using an HPC, but that shouldn't really make a difference, right?

Thanks again for your help,
Carmen

**Comment by DanRunfola** [comment]
Correct, HPC shouldn't matter.

Let's see if Rohith, who is developing the update, has a quick idea/fix
here. @rohith4444 can you replicate or give a suggestion on a fix?

**Comment by dickoa** [comment]
Hi @DanRunfola @cpwebster 

I took a look at it, and made some changes. Can you try this version (not yet merged)

```r
pak::pkg_install("wmgeolab/rgeoboundaries@refactor-new-api")
```

Best,
Ahmadou

**Comment by cpwebster** [comment]
Thanks so much for your help @dickoa , it looks like there might have been some dependency issues? I ran the execution above to install rgeoboundaries and here is the tail end of the output:

```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/tmp/RtmpBl4Oyb/pkg-lib429de1ad423fc/sf/libs/sf.so':
  /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/tmp/RtmpBl4Oyb/pkg-lib429de1ad423fc/sf’
---
Backtrace:
1. pak::pkg_install("wmgeolab/rgeoboundaries@refactor-new-api")
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(new_pkg_build_error("Failed to build source package {pkg}", …
11. | base::signalCondition(cond)
12. global (function (e) …
```
Any direction is appreciated!
Carmen

**Comment by DanRunfola** [comment]
FYI @dickoa I just gave you maintainer privleges on this repo, _very_ glad to see you :)

**Comment by dickoa** [comment]
@cpwebster it looks like an `sf` issue or something relate to your `openssl` install.  Which OS are you using? 
If you're using Linux or Mac OSX, you can check the version of `openssl`, `krb5`, `krb5crypto`, etc. Can you try to reinstall `sf` from CRAN again?

**Comment by cpwebster** [comment]
The issue with `sf` ended up going a little deeper on the HPC that I am using, however- the new API with `rgeoboundaries` is now working beautifully! Thank you so much to both of you, @DanRunfola and @dickoa , for all of your help, I really appreciate it. 

Thank you again and take care,
Carmen

**Comment by DanRunfola** [comment]
@cpwebster Great!  Please let us know if you run into any other issues.

@dickoa thank you again!
